### ISSUE TITLE
服务端渲染项目使用有问题

### ISSUE THREAD

**Issue by chenbeier** [tong233/react-bullet-screen#1]
您好，我这react项目采用的是服务端渲染，以下代码：
`constructor(props) {
    super(props)
    this.launchedCount = 0 // 已经发射的弹幕数
    this.srollWidth = document.body.clientWidth
  }`
中document获取到，这行需要放在componentDidmount里执行，麻烦修改一下~

**Comment by tong233** [comment]
不好意思老哥，改的有点晚，v0.1.2
